name: ECR Push

on:
  push:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name to build'
        required: true
        type: string
      version:
        description: 'Version/tag for the image'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push image
        uses: docker/actions/build-push-image-ecr@build-push-image-ecr/v1
        with:
          dockerfile: Dockerfile
          docker_password: ${{ secrets.DOCKERBUILDBOT_READ_PAT }}
          image_name: ${{ inputs.service }}
          image_version: ${{ inputs.version }}