name: ECR Push

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name to build'
        required: true
        type: string
      version:
        description: 'Version/tag for the image'
        required: true
        type: string

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push image
        uses: docker/actions/build-push-image-ecr@build-push-image-ecr/v1
        with:
          docker_password: ${{ secrets.DOCKERBUILDBOT_READ_PAT }}
          image_name: 'hello-world'
          image_version: '1.0'