name: ECR Push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version/tag for the image'
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and push image
        uses: docker/actions/build-push-image-ecr@build-push-image-ecr/v1
        with:
          docker_password: ${{ secrets.DOCKERBUILDBOT_READ_PAT }}
          image_name: 'hello-world'
          image_version: ${{ inputs.tag }}