name: Package Safetensors model

on:
  workflow_dispatch:
    inputs:
      # Single model inputs
      huggingface_repository:
        description: 'HuggingFace repository (e.g., HuggingFaceTB/SmolLM2-135M-Instruct)'
        required: false
        type: string
      registry_repository:
        description: 'OCI Registry repository'
        required: false
        type: string
      weights:
        description: 'Model weights tag (e.g., 7B, 13B, medium)'
        required: false
        type: string
      quantization:
        description: 'Quantization type (e.g., Q4_K_M, Q8_0, F16)'
        required: false
        type: string
        default: 'Q4_K_M'
      llama_cpp_tag:
        description: 'Llama.cpp Docker image tag'
        required: true
        type: string
        default: 'full-b5763'
      license_url:
        description: 'URL to the license file'
        required: false
        type: string
      # Multi-model input
      models_json:
        description: 'JSON array of models to package (alternative to single model inputs). Format: [{"hf_repository":"HuggingFaceTB/SmolLM2-135M-Instruct", "repository":"repo", "weights":"135M", "quantization":"Q4_K_M", "license_url":"https://huggingface.co/datasets/choosealicense/licenses/resolve/main/markdown/apache-2.0.md"}]'
        required: false
        type: string

permissions:
  contents: read

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate matrix
        id: set-matrix
        run: |
          if [ -n "${{ inputs.models_json }}" ]; then
            # Use the provided JSON array
            echo '${{ inputs.models_json }}' > models.json
          elif [ -n "${{ inputs.huggingface_repository }}" ]; then
            # Create single-item array for single model
            single_model='[{"hf_repository":"${{ inputs.huggingface_repository }}", "repository":"${{ inputs.registry_repository }}", "weights":"${{ inputs.weights }}", "quantization":"${{ inputs.quantization }}", "llama_cpp_tag":"${{ inputs.llama_cpp_tag }}", "license_url":"${{ inputs.license_url }}"}]'
            echo "$single_model" > models.json
          else
            echo "Error: Either provide single model inputs (huggingface_repository, registry_repository, weights) or models_json array"
            exit 1
          fi
          
          # Validate JSON format
          if ! jq empty models.json 2>/dev/null; then
            echo "Error: Invalid JSON format in models_json input"
            exit 1
          fi
          
          # Convert JSON array to GitHub Actions matrix format
          # Each model becomes a separate matrix item with individual properties
          matrix_json=$(jq -r '.[] | {
            hf_repository: .hf_repository,
            repository: .repository,
            weights: .weights,
            quantization: .quantization,
            llama_cpp_tag: "'${{ inputs.llama_cpp_tag }}'",
            license_url: .license_url
          }' models.json | jq -s 'map(.)' | jq -c '.')
          
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

  package:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_STAGING }}
          password: ${{ secrets.DOCKER_OAT_STAGING }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "${{ secrets.DOCKER_USER_STAGING }}/default"
          install: true

      - name: Build and push model
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.safetensors
          platforms: 'linux/amd64'
          build-args: |          
            HUGGINGFACE_REPOSITORY=${{ matrix.model.hf_repository }}
            LICENSE=${{ matrix.model.license_url }}
            HUB_REPOSITORY=${{ secrets.DOCKER_USER_STAGING }}/${{ matrix.model.repository }}
            WEIGHTS=${{ matrix.model.weights }}
            QUANTIZATION=${{ matrix.model.quantization }}
            LLAMA_CPP_TAG=${{ matrix.model.llama_cpp_tag }}
          secrets: |
            DOCKER_USERNAME=${{ secrets.DOCKER_USER_STAGING }}
            DOCKER_PASSWORD=${{ secrets.DOCKER_OAT_STAGING }}
            HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}
