name: Package Model

on:
  workflow_dispatch:
    inputs:
      hf_repository:
        description: 'HuggingFace repository (e.g., HuggingFaceTB/SmolLM2-135M-Instruct)'
        required: true
        type: string
        default: 'HuggingFaceTB/SmolLM2-135M-Instruct'
      quantization:
        description: 'Quantization type (e.g., Q4_K_M, Q8_0, F16)'
        required: true
        type: string
        default: 'F16'
      weights:
        description: 'Weights of the model (e.g., 135M, 3B, 70B)'
        required: true
        type: string
        default: '135M'
      registry_repository:
        description: 'OCI Registry repository'
        required: true
        type: string
        default: 'smollm2'
      input_types:
        description: 'Comma-separated input types (e.g., text,embedding,image)'
        required: true
        type: string
        default: 'text'
      output_types:
        description: 'Comma-separated output types (e.g., text,embedding,image)'
        required: true
        type: string
        default: 'text'
      tool_usage:
        description: 'Enable tool usage support'
        required: false
        type: boolean
        default: false
      license:
        description: 'Url to the license file'
        required: true
        type: string
        default: 'https://huggingface.co/datasets/choosealicense/licenses/resolve/main/markdown/apache-2.0.md'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "docker/default"
          install: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ inputs.registry_repository }}:${{ inputs.weights }}-${{ inputs.quantization }}
          build-args: |          
            HUGGINGFACE_REPOSITORY=${{ inputs.hf_repository }}
            QUANTIZATION=${{ inputs.quantization }}
            WEIGHTS=${{ inputs.weights }}
            HUB_REPOSITORY=${{ vars.DOCKER_USER }}/${{ inputs.registry_repository }}
            LICENSE=${{ inputs.license }}
          secrets: |
            HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}
            DOCKER_USERNAME=${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD=${{ secrets.DOCKER_PAT }}
